openapi: 3.0.0
info:
  title: Ecommerce Api
  version: 0.1.0
  description: This is the contract for Ecommerce api
components:
  ErrorResponse:
    $ref: "@/schemas/common/ErrorResponse.yaml"
  SuccessResponse:
    $ref: "@/schemas/common/SuccessResponse.yaml"
paths:
  /api/user/verify:
    $ref: "@/paths/user/Verify.yaml"
  /api/user/register:
    $ref: "@/paths/user/Register.yaml"
  /api/user/login:
    $ref: "@/paths/user/Login.yaml"

  /api/user/address:
    $ref: "@/paths/address/GetAddresses.yaml"
  /api/user/address/add:
    $ref: "@/paths/address/AddAddress.yaml"
  /api/user/address/edit/{address_id}: 
    $ref: "@/paths/address/EditAddress.yaml"
  /api/user/address/delete/{address_id}: 
    $ref: "@/paths/address/DeleteAddress.yaml"

  /api/products:
    $ref: "@/paths/product/GetProducts.yaml"
  /api/product/{product_id}:
    $ref: "@/paths/product/GetProductById.yaml"
  /api/product/add:
    $ref: "@/paths/product/AddProduct.yaml"
  /api/product/edit/{product_id}:
    $ref: "@/paths/product/EditProduct.yaml"
  /api/product/delete/{product_id}:
    $ref: "@/paths/product/DeleteProduct.yaml"

  /api/orders:
    $ref: "@/paths/order/GetOrders.yaml"
  /api/order/{order_id}:
    $ref: "@/paths/order/GetOrderById.yaml"
  /api/order/place:
    $ref: "@/paths/order/PlaceOrder.yaml"

  /api/reviews/{product_id}:
    $ref: "@/paths/review/GetReviewsByProductId.yaml"
  /api/review/add:
    $ref: "@/paths/review/AddReview.yaml"
  /api/review/edit/{review_id}: 
    $ref: "@/paths/review/EditReview.yaml"
  /api/review/delete/{review_id}: 
    $ref: "@/paths/review/DeleteReview.yaml"