openapi: 3.0.0
info:
  title: Ecommerce Api
  version: 0.1.0
  description: This is the contract for Ecommerce api
components:
  schemas:
    ErrorResponse:
      $ref: "@/schemas/common/ErrorResponse.yaml"
    SuccessResponse:
      $ref: "@/schemas/common/SuccessResponse.yaml"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/user/signup:
    post:
      $ref: "@/paths/user/Signup.yaml"

  /api/user/signin:
    post:
      $ref: "@/paths/user/Signin.yaml"

  /api/user/address:
    get:
      $ref: "@/paths/address/GetAddresses.yaml"
    post:
      $ref: "@/paths/address/AddAddress.yaml"
  /api/user/address/{address_id}:
    put:
      $ref: "@/paths/address/EditAddress.yaml"
    delete:
      $ref: "@/paths/address/DeleteAddress.yaml"

  /api/product:
    get:
      $ref: "@/paths/product/GetProducts.yaml"
    post:
      $ref: "@/paths/product/AddProduct.yaml"

  /api/product/{product_id}:
    get:
      $ref: "@/paths/product/GetProductById.yaml"
    put:
      $ref: "@/paths/product/EditProduct.yaml"
    delete:
      $ref: "@/paths/product/DeleteProduct.yaml"

  /api/cart:
    get:
      $ref: "@/paths/cart/GetCart.yaml"
    post:
      $ref: "@/paths/cart/AddToCart.yaml"
  /api/cart/{cart_id}:
    put:
      $ref: "@/paths/cart/EditCart.yaml"
    delete:
      $ref: "@/paths/cart/DeleteCart.yaml"

  /api/order:
    get:
      $ref: "@/paths/order/GetOrders.yaml"
    post:
      $ref: "@/paths/order/PlaceOrder.yaml"
  /api/order/{order_id}:
    get:
      $ref: "@/paths/order/GetOrderById.yaml"

  /api/review:
    post:
      $ref: "@/paths/review/AddReview.yaml"
  /api/review/{review_id}:
    put:
      $ref: "@/paths/review/EditReview.yaml"
    delete:
      $ref: "@/paths/review/DeleteReview.yaml"
